# Generated by Django 4.1 on 2022-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_system', '0001_initial'),
        ('employee', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='surveys',
            field=models.ManyToManyField(through='survey_system.EmployeeSurvey', to='survey_system.survey'),
        ),
    ]
