# Generated by Django 4.1 on 2022-09-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_surveys_alter_employee_user'),
        ('survey_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesurvey',
            name='get_rated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_rated', to='employee.employee'),
        ),
    ]
