# Generated by Django 4.1 on 2022-09-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quetion',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='employeesurvey',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='employeesurvey',
            name='object_id',
        ),
    ]
