# Generated by Django 4.1 on 2022-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_system', '0002_alter_employeesurvey_get_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
