# Generated by Django 4.1 on 2022-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_system', '0003_survey_title_alter_employeesurvey_rater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
